[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
console_error_panic_hook = "*"
shuttle_runtime = "0.1.0"


[dependencies.web-sys]
version = "0.3.77"
features = ["console"]
